### ISSUE TITLE
ValueError when parsing config.

### ISSUE THREAD

**Issue by gvalkov** [hackebrot/poyo#9]
Hello @hackebrot,

I'm trying out poyo as a replacement for pyyaml in one of [my projects](https://github.com/gvalkov/tailon). The project's config file looks more or less like this:

```yaml
bind: 0.0.0.0:8081      # address and port to bind on
allow-transfers: true   # allow log file downloads
relative-root: /        # web app root path (default: '')
commands: [tail, grep]  # allowed commands
wrap-lines: true        # initial line-wrapping state

files:
  - 'logs/apache/www.tailon.org/'
```

This currently breaks poyo in two places:

1) Poyo tries to parse `0.0.0.0:8081` as a float.  Here's the debug output I added to `read_from_tag() `:

```
pattern: '(?P<quotes>[\'\\"]?).*(?P=quotes)'
group:  'bind'
string: 'bind'

pattern: '([-+]?(\\.[0-9]+|[0-9]+(\\.[0-9]*)?)([eE][-+]?[0-9]+)?)'
group:  '0.0'
string: '0.0.0.0:8081'
```

Perhaps the regex can be fixed or `read_from_tag()` can continue trying patterns until the one that matches most 'fully' is found?

2) The `relative-root: /        # web app root path (default: '')` line breaks the parser, because of the `:` in the comment:
```
pattern: '(?P<quotes>[\'\\"]?).*(?P=quotes)'
group:  'relative-root: "/"    # web app root path (default'
string: 'relative-root: "/"    # web app root path (default'

pattern: '(?P<quotes>[\'\\"]?).*(?P=quotes)'
group:  "''"
string: "''"
```

Kind regards,
Georgi
